/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Empleado;

import Modelo.Clases.Usuario;
import Vista.Socio.PantallaPrincipalSocio;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Fernando
 */
public class PantallaPrincipalEmpleado extends javax.swing.JFrame {

    Usuario usuarioLogueado;

    public PantallaPrincipalEmpleado(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setImageLabel(jLabelLogo, "/img/logo.png");
        this.setFondoPantalla();
        this.setResizable(false);
    }

    private void setImageLabel(JLabel label, String ruta) {
        try {
            // Carga de la imagen desde la ruta proporcionada
            ImageIcon imagen = new ImageIcon(getClass().getResource(ruta));

            // Verificar si la imagen se ha cargado correctamente
            if (imagen.getIconWidth() == -1) {
                System.out.println("No se pudo cargar la imagen desde la ruta: " + ruta);
                return; // Salimos si la imagen no se cargó
            }

            // Obtener la imagen original
            Image img = imagen.getImage();

            // Redimensionar la imagen para que se ajuste al tamaño del JLabel
            Image imagenRedimensionada = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);

            // Crear un nuevo ImageIcon con la imagen redimensionada
            ImageIcon imagenRedimensionada2 = new ImageIcon(imagenRedimensionada);

            // Establecer el icono de la etiqueta
            label.setIcon(imagenRedimensionada2);
        } catch (Exception e) {
            e.printStackTrace(); // Imprimir cualquier excepción que ocurra
        }
    }

    private void setFondoPantalla() {
        // Carga la imagen de fondo desde el archivo
        ImageIcon fondo = new ImageIcon(getClass().getResource("/img/fondo.jpg"));

        // Obtenemos la imagen original
        Image img = fondo.getImage();

        // Redimensionamos la imagen para que se ajuste al tamaño del JFrame manteniendo la proporción
        Image fondoRedimensionado = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);

        // Creamos un nuevo ImageIcon con la imagen redimensionada
        ImageIcon fondoRedimensionadoIcon = new ImageIcon(fondoRedimensionado);

        // Creamos un JLabel que contiene la imagen redimensionada
        JLabel fondoLabel = new JLabel(fondoRedimensionadoIcon);

        // Configuramos el JLabel al tamaño del JFrame
        fondoLabel.setSize(this.getWidth(), this.getHeight());

        // Agregamos el JLabel al JPanel del JFrame
        this.getContentPane().add(fondoLabel);

        // Para que los otros componentes aparezcan encima del fondo, ajustamos el layout
        this.getContentPane().setLayout(null);  // Desactivar el layout automático para colocar manualmente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemVerLibros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemClubs = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Informes = new javax.swing.JMenu();
        InformeEventos = new javax.swing.JMenuItem();
        InformeSocios = new javax.swing.JMenuItem();
        EjemplaresInforme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido/a");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Al panel del empleado de ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Biblioteca Oliveria");

        jMenu1.setText("Libros");

        jMenuItemVerLibros.setText("Ver");
        jMenuItemVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerLibrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVerLibros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eventos");

        jMenuItem1.setText("Ver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Club de Lectura");

        jMenuItemClubs.setText("Buscar");
        jMenuItemClubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClubsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemClubs);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Socios");

        jMenuItem3.setText("Ver");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        Informes.setText("Informes");

        InformeEventos.setText("Eventos");
        InformeEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeEventosActionPerformed(evt);
            }
        });
        Informes.add(InformeEventos);

        InformeSocios.setText("Socios");
        InformeSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeSociosActionPerformed(evt);
            }
        });
        Informes.add(InformeSocios);

        EjemplaresInforme.setText("Ejemplares");
        EjemplaresInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjemplaresInformeActionPerformed(evt);
            }
        });
        Informes.add(EjemplaresInforme);

        jMenuBar1.add(Informes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerLibrosActionPerformed
        try {
            BuscarLibrosVistaEmp vista = new BuscarLibrosVistaEmp(usuarioLogueado);
            vista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemVerLibrosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            EventosVistaEmp vista = new EventosVistaEmp(usuarioLogueado);
            vista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClubsActionPerformed
        try {
            ClubVistaEmp clubVista = new ClubVistaEmp(usuarioLogueado);
            clubVista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemClubsActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            SociosVistaEmp vistaSocios = new SociosVistaEmp(usuarioLogueado);
            vistaSocios.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipalEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void InformeSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeSociosActionPerformed
        try {
            JasperCompileManager.compileReportToFile("src/main/java/Informes/Socios/socios.jrxml");
            JasperReport report = (JasperReport) JRLoader.loadObjectFromFile("src/main/java/Informes/Socios/socios.jasper");

            Connection conn = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Biblioteca", "root", "1234");
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
            }

            JasperPrint printer = JasperFillManager.fillReport(report, null, conn);
            JasperViewer.viewReport(printer);
        } catch (JRException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InformeSociosActionPerformed

    private void InformeEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeEventosActionPerformed
        try {
            JasperCompileManager.compileReportToFile("src/main/java/Informes/Eventos/eventos.jrxml");
            JasperReport report = (JasperReport) JRLoader.loadObjectFromFile("src/main/java/Informes/Eventos/eventos.jasper");

            Connection conn = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Biblioteca", "root", "1234");
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
            }

            JasperPrint printer = JasperFillManager.fillReport(report, null, conn);
            JasperViewer.viewReport(printer);
        } catch (JRException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InformeEventosActionPerformed

    private void EjemplaresInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjemplaresInformeActionPerformed
        try {
            JasperCompileManager.compileReportToFile("src/main/java/Informes/Ejemplares/ejemplares.jrxml");
            JasperReport report = (JasperReport) JRLoader.loadObjectFromFile("src/main/java/Informes/Ejemplares/ejemplares.jasper");

            Connection conn = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Biblioteca", "root", "1234");
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
            }

            JasperPrint printer = JasperFillManager.fillReport(report, null, conn);
            JasperViewer.viewReport(printer);
        } catch (JRException ex) {
            Logger.getLogger(PantallaPrincipalSocio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EjemplaresInformeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EjemplaresInforme;
    private javax.swing.JMenuItem InformeEventos;
    private javax.swing.JMenuItem InformeSocios;
    private javax.swing.JMenu Informes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemClubs;
    private javax.swing.JMenuItem jMenuItemVerLibros;
    // End of variables declaration//GEN-END:variables
}
